"""Structured OTA encoding operation helpers and replay validation."""

from encoding.operations import (
    OPERATION_SUPPORT,
    DeltaCodec,
    OperationSupport,
    OperationType,
    block_sha256,
    bytes_sha256,
    decode_bytes,
    encode_bytes,
    make_append_operation,
    make_backup_operation,
    make_checkpoint_operation,
    make_commit_operation,
    make_copy_operation,
    make_delete_operation,
    make_delta_operation,
    make_keep_operation,
    make_raw_insert_operation,
    make_rollback_operation,
    make_skip_operation,
    make_truncate_operation,
    make_verify_operation,
)

__all__ = [
    "DeltaCodec",
    "OPERATION_SUPPORT",
    "OperationSupport",
    "OperationType",
    "block_sha256",
    "bytes_sha256",
    "decode_bytes",
    "encode_bytes",
    "make_append_operation",
    "make_backup_operation",
    "make_checkpoint_operation",
    "make_commit_operation",
    "make_copy_operation",
    "make_delete_operation",
    "make_delta_operation",
    "make_keep_operation",
    "make_raw_insert_operation",
    "make_rollback_operation",
    "make_skip_operation",
    "make_truncate_operation",
    "make_verify_operation",
]
